name: 'Automatic build'
on:
  push:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  continuous-delivery:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true   # 临时解决 Node 20 警告
      JEKYLL_ENV: production

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2
          bundler-cache: true

      - name: Check baseurl
        run: |
          baseurl="$(grep '^baseurl:' _config.yml | sed "s/.*: *//;s/['\"]//g;s/#.*//")"
          if [[ -n $baseurl ]]; then
            echo "SPEC_TEST=_site_no_baseurl" >> $GITHUB_ENV
          fi

      - name: Build Site
        run: |
          bundle exec jekyll b
          if [[ -n $SPEC_TEST ]]; then
            bundle exec jekyll b -b "" -d "$SPEC_TEST"
          fi

      - name: Test Site
        run: |
          if [[ -n $SPEC_TEST ]]; then
            bash tools/test.sh -d "$SPEC_TEST"
          else
            bash tools/test.sh
          fi

      - name: Deploy
        run: |
          bash tools/deploy.sh